services:
  crusher:
    image: ghcr.io/siahmurph/crusher:latest
    container_name: crusher
    ports:
      - "8030:3000"
    volumes:
      - /var/crusher:/data
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - portainer_default
    environment:
      PORTAINER_URLS: http://portainer:9000,http://host.docker.internal:9000
      PORTAINER_API_KEY: ${PORTAINER_API_KEY}
      PORTAINER_ENDPOINT: "3"

networks:
  portainer_default:
    external: true
