services:
  crusher:
    image: ghcr.io/siahmurph/crusher:latest
    container_name: crusher
    ports:
      - "8030:3000"
    volumes:
      - /var/crusher:/data
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - PORTAINER_URL=http://10.8.1.130:9000
      - PORTAINER_API_KEY=ptr_nt8z8SiZJPfPICOTtdqUyNbyBAAzzimalIwUSFGyZek=
      - PORTAINER_ENDPOINT=1
